---
title: "Presentation Ninja"
subtitle: "&#x2694;&#xFE0F; xaringan +<br/>&#x1F60E; xaringanthemer"  
author: 
  - "Yihui Xie"
  - "Garrick Aden-Buie"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF"
)
```


```{r source, echo=FALSE, message=FALSE, warning=FALSE, include=TRUE}
library(here)
source(here::here("01_src", "01_initialise.R"))
source(here::here("01_src", "02_data_import.R"))
source(here::here("01_src", "03_wrangle.R"))
source(here::here("01_src", "04_analysis.R"))
source(here::here("01_src", "05_figures.R"))
```

```{r}

```


---



```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE, fig.height=8, fig.width=8, fig.retina=2}

```


---



```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE, fig.height=8, fig.width=8, fig.retina=2}

```


---